modLoader = "javafml"
loaderVersion = "[24,)"
license = "All Rights Reserved"
authors = "LatvianModder"
[[mods]]
modId = "modularpipes"
version = "${version}"
displayName = "Modular Pipes"
description = '''sick pipes init' fam'''