modLoader = "javafml"
loaderVersion = "[24,)"
authors = "LatvianModder"
[[mods]] #mandatory
modId = "modularpipes"
version = "${version}"
displayName = "Modular Pipes"
description = '''sick pipes init' fam'''